"""
Module 15 — Automated report generator.

Produces a Word (.docx) investor/executive report and an Excel summary from the
computed analytics + agent narratives.
"""
from __future__ import annotations
import pandas as pd
from config.config import get_logger, REPORTS_DIR

log = get_logger("report_generator")


def build_docx(context: dict) -> str:
    from docx import Document
    from docx.shared import Pt, RGBColor
    doc = Document()
    doc.add_heading("Auto Loan Securitisation — Risk Analytics Report", 0)
    doc.add_paragraph("Pool ZAAUTO2024-1 | Generated by the Securitisation AI Agent pipeline.")

    doc.add_heading("1. Executive Summary", 1)
    doc.add_paragraph(context["health"])

    doc.add_heading("2. IFRS 9 / ECL", 1)
    doc.add_paragraph(context["ecl_explain"])
    _table_from_df(doc, context["ifrs9_summary"])

    doc.add_heading("3. Delinquency (DPD)", 1)
    _table_from_df(doc, context["dpd_distribution"])

    doc.add_heading("4. Vintage / Static Pool", 1)
    _table_from_df(doc, context["vintage_summary"].head(8))

    doc.add_heading("5. Stress Testing", 1)
    _table_from_df(doc, context["stress"])

    doc.add_heading("6. Investor Summary", 1)
    doc.add_paragraph(context["investor"])

    doc.add_heading("7. Model Validation Note", 1)
    doc.add_paragraph(context["validation_note"])

    path = REPORTS_DIR / "Securitisation_Risk_Report.docx"
    doc.save(path)
    log.info("Word report saved: %s", path.name)
    return str(path)


def _table_from_df(doc, df: pd.DataFrame):
    df = df.copy().round(4)
    t = doc.add_table(rows=1, cols=len(df.columns))
    t.style = "Light Grid Accent 1"
    for j, c in enumerate(df.columns):
        t.rows[0].cells[j].text = str(c)
    for _, row in df.iterrows():
        cells = t.add_row().cells
        for j, v in enumerate(row):
            cells[j].text = f"{v:,.4f}" if isinstance(v, float) else str(v)


def build_excel_summary(context: dict) -> str:
    path = REPORTS_DIR / "Securitisation_Summary.xlsx"
    sheets = {"IFRS9_ECL": context["ifrs9_summary"], "DPD": context["dpd_distribution"],
              "Vintage": context["vintage_summary"], "Stress": context["stress"]}
    with pd.ExcelWriter(path, engine="openpyxl") as xw:
        for name, df in sheets.items():
            (df if df is not None and not df.empty else pd.DataFrame({"note": ["no data"]})).to_excel(xw, name, index=False)
    log.info("Excel summary saved: %s", path.name)
    return str(path)
